/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DataPointUpdateManyWithoutSensorsInput } from "./DataPointUpdateManyWithoutSensorsInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { DeviceWhereUniqueInput } from "../../device/base/DeviceWhereUniqueInput";
import { DeviceUpdateManyWithoutSensorsInput } from "./DeviceUpdateManyWithoutSensorsInput";
import { FarmWhereUniqueInput } from "../../farm/base/FarmWhereUniqueInput";
import { EnumSensorTypeField } from "./EnumSensorTypeField";

@InputType()
class SensorUpdateInput {
  @ApiProperty({
    required: false,
    type: () => DataPointUpdateManyWithoutSensorsInput,
  })
  @ValidateNested()
  @Type(() => DataPointUpdateManyWithoutSensorsInput)
  @IsOptional()
  @Field(() => DataPointUpdateManyWithoutSensorsInput, {
    nullable: true,
  })
  dataPoints?: DataPointUpdateManyWithoutSensorsInput;

  @ApiProperty({
    required: false,
    type: () => DeviceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeviceWhereUniqueInput)
  @IsOptional()
  @Field(() => DeviceWhereUniqueInput, {
    nullable: true,
  })
  device?: DeviceWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DeviceUpdateManyWithoutSensorsInput,
  })
  @ValidateNested()
  @Type(() => DeviceUpdateManyWithoutSensorsInput)
  @IsOptional()
  @Field(() => DeviceUpdateManyWithoutSensorsInput, {
    nullable: true,
  })
  devices?: DeviceUpdateManyWithoutSensorsInput;

  @ApiProperty({
    required: false,
    type: () => FarmWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FarmWhereUniqueInput)
  @IsOptional()
  @Field(() => FarmWhereUniqueInput, {
    nullable: true,
  })
  farm?: FarmWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumSensorTypeField,
  })
  @IsEnum(EnumSensorTypeField)
  @IsOptional()
  @Field(() => EnumSensorTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;
}

export { SensorUpdateInput as SensorUpdateInput };
